INSERT INTO CATALOG(PRODUCT_ID, PRODUCT_NAME, STOCK, UNIT_PRICE) VALUES ('CATALOG-001','Berlin',100,1500);
INSERT INTO CATALOG(PRODUCT_ID, PRODUCT_NAME, STOCK, UNIT_PRICE) VALUES ('CATALOG-002','Tokyo',200,2500);
INSERT INTO CATALOG(PRODUCT_ID, PRODUCT_NAME, STOCK, UNIT_PRICE) VALUES ('CATALOG-003','Seoul',300,3500);
INSERT INTO CATALOG(PRODUCT_ID, PRODUCT_NAME, STOCK, UNIT_PRICE) VALUES ('CATALOG-004','Busan',400,4500);
INSERT INTO CATALOG(PRODUCT_ID, PRODUCT_NAME, STOCK, UNIT_PRICE) VALUES ('CATALOG-005','LA',500,5500);
INSERT INTO CATALOG(PRODUCT_ID, PRODUCT_NAME, STOCK, UNIT_PRICE) VALUES ('CATALOG-006','NewYork',600,6500);